BOARD_TAG=uno
ARDUINO_DIR=/usr/local/arduino/
USER_LIB_PATH=/usr/local/arduino-libraries/
#/home/james/local/arduino/libraries/
ARDUINO_LIBS=Wire LiquidCrystal DS1307RTC Time TimeAlarms

include /usr/local/arduino/Arduino-Makefile/Arduino.mk

